const LIMITS = {
  SLUG_MAX_LENGTH: 60,
  URL_MAX_LENGTH: 2048,
  SHAPE_COUNT_MAX: 10,
  SHAPE_COUNT_MIN: 0,
  TOTAL_INSTANCES_MAX: 40,
  SIZE_MIN: 0.1,
  SIZE_MAX: 10.0,
  STROKE_WEIGHT_MIN: 0,
  STROKE_WEIGHT_MAX: 20,
  ADMIN_KEY_LENGTH: 32,
  TEXTURE_DATA_URL_MAX_SIZE: 5_000_000,
  CAMERA_Z_MIN: 1.0,
  CAMERA_Z_MAX: 2000.0,
  ROTATION_SPEED_MIN: -1.0,
  ROTATION_SPEED_MAX: 1.0,
  LEGACY_COUNT_MIN: 1,
  LEGACY_COUNT_MAX: 500,
  DB_TIMEOUT_SECONDS: 2,
  SLUG_RETRY_ATTEMPTS: 5,
  RATE_LIMIT_MAX_REQUESTS: 10,
  RATE_LIMIT_WINDOW_SECONDS: 60,
};

const ALLOWED_SHAPES = ['box', 'sphere', 'cone', 'torus'];
const ALLOWED_VISIBILITY = ['public', 'unlisted', 'deleted'];
const ALLOWED_IMAGE_EXTENSIONS = ['.png', '.jpg', '.jpeg', '.webp'];

module.exports = {
  LIMITS,
  ALLOWED_SHAPES,
  ALLOWED_VISIBILITY,
  ALLOWED_IMAGE_EXTENSIONS,
};
